/**
 * Writes typed ABIs for every Intatto contract from the forge build output into config/abi/.
 * Run after `forge build --root contracts`: `pnpm abi`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const outDir = join(root, "config", "abi")

const CONTRACTS = [
  "LendingVault",
  "CollateralMarket",
  "GapReserve",
  "InterestRateModel",
  "MarketLens",
  "SessionRiskController",
  "DepthCapRegistry",
  "PriceRelayAdapter",
  "CorporateActionGuard",
  "BoundedLiquidator",
  "ChainlinkV10Adapter",
] as const

mkdirSync(outDir, { recursive: true })
const index: string[] = []
for (const name of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"))
  const constName = `${name[0].toLowerCase()}${name.slice(1)}Abi`
  writeFileSync(
    join(outDir, `${name}.ts`),
    `// Generated by config/scripts/export-abi.ts from contracts/out. Do not edit.\nexport const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const\n`,
  )
  index.push(`export { ${constName} } from "./${name}.ts"`)
}
writeFileSync(join(outDir, "index.ts"), `${index.join("\n")}\n`)
process.stdout.write(`wrote ${CONTRACTS.length} ABIs to config/abi\n`)
