/**
 * Build-time generator (Node only, never bundled): copies each Intatto contract's runtime bytecode and the
 * byte ranges of its immutables from contracts/out into artifacts.generated.ts, so the fork proof page can
 * compare the sandbox's code with what this repo builds (immutables are masked on both sides).
 *
 *   npx tsx web/components/fork-proof/generate-artifacts.ts
 *
 * The fork-proof check runs it after the fork harness has compiled and deployed, so both come from one build.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { ARTIFACT_NAMES } from "./intatto-contracts.ts"

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, "..", "..", "..")
export const GENERATED_PATH = join(HERE, "artifacts.generated.ts")

type ForgeArtifact = {
  deployedBytecode: {
    object: string
    immutableReferences?: Record<string, { start: number; length: number }[]>
    linkReferences?: Record<string, unknown>
  }
  metadata?: { compiler?: { version?: string }; settings?: { optimizer?: { enabled?: boolean; runs?: number }; evmVersion?: string } }
}

function readArtifact(name: string): ForgeArtifact {
  const path = join(REPO, "contracts", "out", `${name}.sol`, `${name}.json`)
  if (!existsSync(path)) throw new Error(`missing build artifact ${path}: run \`forge build --root contracts\` first`)
  return JSON.parse(readFileSync(path, "utf8")) as ForgeArtifact
}

/** Renders the generated module's source. */
export function renderArtifactsModule(): string {
  let compiler = "unknown"
  const entries: string[] = []
  for (const name of ARTIFACT_NAMES) {
    const a = readArtifact(name)
    const code = a.deployedBytecode.object
    if (!/^0x[0-9a-fA-F]*$/.test(code) || code.length <= 2) throw new Error(`${name}: deployedBytecode is not plain hex`)
    if (a.deployedBytecode.linkReferences && Object.keys(a.deployedBytecode.linkReferences).length > 0) {
      throw new Error(`${name}: linked libraries are not supported by the fork proof`)
    }
    const ranges = Object.values(a.deployedBytecode.immutableReferences ?? {})
      .flat()
      .map((r) => [r.start, r.length] as const)
      .sort((x, y) => x[0] - y[0])
    const m = a.metadata
    if (m?.compiler?.version) {
      const opt = m.settings?.optimizer
      compiler = `solc ${m.compiler.version}, optimizer ${opt?.enabled ? `on (${opt.runs} runs)` : "off"}, evm ${m.settings?.evmVersion ?? "default"}`
    }
    entries.push(
      `  ${name}: {\n    source: "contracts/out/${name}.sol/${name}.json",\n    immutables: ${JSON.stringify(ranges)},\n    bytecode:\n      "${code.toLowerCase()}",\n  },`,
    )
  }
  return [
    "// Generated by generate-artifacts.ts from contracts/out. Do not edit by hand; rerun the generator.",
    'import type { ArtifactName } from "./intatto-contracts"',
    "",
    "export type BuildArtifact = {",
    "  source: string",
    "  /** [start, length] byte ranges the constructor fills in; masked before comparing. */",
    "  immutables: readonly (readonly [number, number])[]",
    "  bytecode: `0x${string}`",
    "}",
    "",
    `export const ARTIFACTS_COMPILER = ${JSON.stringify(compiler)}`,
    "",
    "export const INTATTO_ARTIFACTS: Record<ArtifactName, BuildArtifact> = {",
    ...entries,
    "}",
    "",
  ].join("\n")
}

/** Writes the module when its content changed; returns whether it did. */
export function writeArtifactsModule(): boolean {
  const next = renderArtifactsModule()
  const current = existsSync(GENERATED_PATH) ? readFileSync(GENERATED_PATH, "utf8") : ""
  if (current === next) return false
  writeFileSync(GENERATED_PATH, next)
  return true
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const changed = writeArtifactsModule()
  process.stdout.write(`${changed ? "wrote" : "unchanged"} ${GENERATED_PATH}\n`)
}
