// Generated by config/scripts/export-abi.ts from contracts/out. Do not edit.
export const marketLensAbi = [
  {
    "type": "function",
    "name": "account",
    "inputs": [
      {
        "name": "m",
        "type": "address",
        "internalType": "contract CollateralMarket"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "a",
        "type": "tuple",
        "internalType": "struct MarketLens.Account",
        "components": [
          {
            "name": "shares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "assets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "valueUsdg",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "ltvBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxLtvBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "borrowCapacity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "healthFactorE18",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "liquidationPriceE18",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "liquidatable",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "walletToken",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletUsdg",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vaultShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vaultAssets",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "market",
    "inputs": [
      {
        "name": "m",
        "type": "address",
        "internalType": "contract CollateralMarket"
      }
    ],
    "outputs": [
      {
        "name": "k",
        "type": "tuple",
        "internalType": "struct MarketLens.Market",
        "components": [
          {
            "name": "session",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "periodChangedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sessionPostedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxLtvBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceE18",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fetchedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "fresh",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "inBand",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "pegOk",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "corporateActionPaused",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "issuerPaused",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "capUsdg",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sliceUsdg",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalDebt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalCollateralValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "assetsPerShare",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "liquidationThresholdBps",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "vault",
    "inputs": [
      {
        "name": "m",
        "type": "address",
        "internalType": "contract CollateralMarket"
      }
    ],
    "outputs": [
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct MarketLens.Vault",
        "components": [
          {
            "name": "idle",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sharePrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "utilizationBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "borrowRateBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "supplyRateBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "reserveBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalDeficit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deficitCount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const
